from __future__ import annotations

import html
import json
import math
from pathlib import Path
from typing import Any

from aetnamem.impact.estimate import cell_rates, estimate_registered_effects


def build_report(
    rows: list[dict[str, Any]],
    verification: dict[str, Any],
    calibration: dict[str, Any] | None = None,
) -> str:
    effects = estimate_registered_effects(rows)
    cells = cell_rates(rows)
    effect_rows = "".join(
        "<tr>"
        f"<td>{html.escape(name)}</td>"
        f"<td>{value.estimate:+.1%}</td>"
        f"<td>{value.lower:+.1%} to {value.upper:+.1%}</td>"
        f"<td>{value.blocks}</td>"
        "</tr>"
        for name, value in effects.items()
    )
    arm_rows = "".join(
        "<tr>"
        f"<td><code>{arm}</code></td>"
        f"<td>{int(value['runs'])}</td>"
        f"<td>{_percent(value['success_rate'])}</td>"
        f"<td>{_number(value['successes_per_dollar'])}</td>"
        f"<td>{_number(value['mean_tokens'])}</td>"
        f"<td>{_number(value['mean_latency_ms'])}</td>"
        f"<td>{int(value['unsafe_actions'])}</td>"
        f"<td>{int(value['false_warnings'])}</td>"
        "</tr>"
        for arm, value in cells.items()
    )
    status = "VERIFIED" if verification.get("valid") else "INCOMPLETE / INVALID"
    observational = (
        "<h2>Randomized versus observational attribution</h2><pre>"
        + html.escape(
            json.dumps(
                calibration.get("confounding_demonstration", {}),
                indent=2,
                sort_keys=True,
            )
        )
        + "</pre><p>The observational comparison is a registered confounding "
        "demonstration, not an experimental arm.</p>"
        if calibration
        else ""
    )
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>AetnaMem Memory Impact</title>
<style>
body{{font:16px system-ui;max-width:1100px;margin:40px auto;padding:0 20px;color:#17202a}}
h1{{color:#163a5f}} .status{{padding:12px;background:#eef5fb;border-left:5px solid #2874a6}}
table{{border-collapse:collapse;width:100%;margin:18px 0 34px}}th,td{{padding:9px;border-bottom:1px solid #ccd6dd;text-align:left}}
code{{background:#edf2f4;padding:2px 5px}} small{{color:#52616b}}
</style></head><body>
<h1>AetnaMem Memory Impact Lab</h1>
<p class="status"><strong>{status}</strong> — {len(rows)} signed outcome records.</p>
<p>Primary estimand: intention-to-treat effect of offering a registered memory-plane bundle.
These results do not attribute causality to an individual memory.</p>
<h2>Memory-plane effects</h2>
<table><thead><tr><th>Plane / interaction</th><th>Effect</th><th>95% interval</th><th>Complete blocks</th></tr></thead>
<tbody>{effect_rows}</tbody></table>
<h2>All 16 arms</h2>
<table><thead><tr><th>WSEP</th><th>Runs</th><th>Success</th><th>Successes / $</th><th>Tokens</th><th>Latency ms</th><th>Unsafe</th><th>False warnings</th></tr></thead>
<tbody>{arm_rows}</tbody></table>
{observational}
<h2>Integrity</h2><pre>{html.escape(json.dumps(verification, indent=2, sort_keys=True))}</pre>
<small>Generated by AetnaMem 0.6.0. Cost and token claims inherit the trust labels in each host receipt.</small>
</body></html>"""


def write_report(
    output: str | Path,
    rows: list[dict[str, Any]],
    verification: dict[str, Any],
    calibration: dict[str, Any] | None = None,
) -> None:
    Path(output).write_text(
        build_report(rows, verification, calibration), encoding="utf-8"
    )


def _percent(value: float) -> str:
    return "n/a" if math.isnan(value) else f"{value:.1%}"


def _number(value: float) -> str:
    return "n/a" if math.isnan(value) else f"{value:.2f}"
