"""Storage protocol used by the provider-neutral decision engine."""

from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Protocol


class DecisionRepository(Protocol):
    def close(self) -> None: ...
    def transaction(self) -> AbstractContextManager[Any]: ...
    def one(self, sql: str, params: tuple[Any, ...]) -> dict[str, Any] | None: ...
    def all(self, sql: str, params: tuple[Any, ...]) -> list[dict[str, Any]]: ...
    def execute(self, sql: str, params: tuple[Any, ...]) -> Any: ...
    def get_case(self, namespace_id: str, case_id: str) -> dict[str, Any] | None: ...
    def get_membership(self, namespace_id: str, case_id: str, principal_id: str) -> dict[str, Any] | None: ...
    def get_artifact(self, namespace_id: str, artifact_id: str) -> dict[str, Any] | None: ...
    def get_revision(self, namespace_id: str, revision_id: str) -> dict[str, Any] | None: ...
    def get_ballot(self, namespace_id: str, ballot_id: str) -> dict[str, Any] | None: ...
    def get_outcome(self, namespace_id: str, outcome_id: str) -> dict[str, Any] | None: ...
    def get_authorization(self, namespace_id: str, authorization_id: str) -> dict[str, Any] | None: ...
    def find_idempotent(self, namespace_id: str, principal_id: str, key: str) -> dict[str, Any] | None: ...
    def list_events(self, namespace_id: str, case_id: str, *, after_sequence: int = 0) -> list[dict[str, Any]]: ...
    def append_audit(self, case: dict[str, Any], event_type: str, actor: str, payload: dict[str, Any]) -> str: ...
    def record_idempotent(self, namespace_id: str, principal_id: str, key: str, command: str, request_digest: str, response: dict[str, Any], created_at: str, case_id: str | None = None) -> None: ...
